/**
 * Remote governance (ADR-0019 §2/§3): a sync remote is valid only when its
 * host is allowlisted (github.com by default; admins append their GitHub
 * Enterprise Server host). Covers HTTPS and SSH remote URL forms. Pure.
 */

export interface RemoteInfo {
  host: string;
  /** "org/repo" with any trailing .git removed. */
  repoPath: string;
  /** Browsable base, e.g. https://github.corp.example/org/repo */
  webBaseUrl: string;
}

/** Parse https://host/org/repo(.git), ssh://git@host/org/repo, git@host:org/repo. */
export function parseRemoteUrl(url: string): RemoteInfo | undefined {
  const trimmed = url.trim();
  const scp = trimmed.match(/^[\w.-]+@([\w.-]+):(.+)$/); // git@host:org/repo
  if (scp) {
    return toInfo(scp[1], scp[2]);
  }
  try {
    const u = new URL(trimmed);
    if (u.protocol === "https:" || u.protocol === "ssh:") {
      return toInfo(u.hostname, u.pathname.replace(/^\/+/, ""));
    }
  } catch {
    // fall through
  }
  return undefined;
}

function toInfo(host: string, path: string): RemoteInfo | undefined {
  const repoPath = path.replace(/\.git$/i, "").replace(/\/+$/, "");
  if (!host || !/^[^/]+\/.+/.test(repoPath)) {
    return undefined;
  }
  return {
    host: host.toLowerCase(),
    repoPath,
    webBaseUrl: `https://${host.toLowerCase()}/${repoPath}`,
  };
}

export interface RemoteVerdict {
  ok: boolean;
  reason?: string;
  info?: RemoteInfo;
}

/** Validate a remote URL against the machine-scoped host allowlist. */
export function validateRemote(url: string, allowedHosts: string[]): RemoteVerdict {
  const info = parseRemoteUrl(url);
  if (!info) {
    return {
      ok: false,
      reason: "Not a recognized git remote URL (expected https://host/org/repo or git@host:org/repo).",
    };
  }
  const allowed = allowedHosts.map((h) => h.trim().toLowerCase()).filter(Boolean);
  if (!allowed.includes(info.host)) {
    return {
      ok: false,
      info,
      reason: `Host "${info.host}" is not in aiSharePoint.sync.allowedRemoteHosts (${allowed.join(", ") || "empty"}). Ask your administrator to allowlist your GitHub / GitHub Enterprise Server host.`,
    };
  }
  return { ok: true, info };
}

/** Compare/PR URL — identical path shape on github.com and GHES. */
export function compareUrl(info: RemoteInfo, baseBranch: string, headBranch: string): string {
  return `${info.webBaseUrl}/compare/${encodeURIComponent(baseBranch)}...${encodeURIComponent(headBranch)}?expand=1`;
}

/** Review-gate branch name for PR-gated pushes (ADR-0019 §3). */
export function prBranchName(nowIso: string): string {
  return `sharepoint-sync/${nowIso.replace(/[-:]/g, "").slice(0, 15)}`; // YYYYMMDDTHHMMSS
}

/** Repo hygiene files written on configure (ADR-0019 §4). */
export function repoHygieneFiles(siteName: string, siteUrl: string): Map<string, string> {
  return new Map([
    [
      ".gitattributes",
      "* text=auto eol=lf\n*.json text eol=lf\n",
    ],
    [
      ".gitignore",
      ".aisharepoint/cache/\n.DS_Store\nThumbs.db\n",
    ],
    [
      "README.md",
      `# ${siteName} — SharePoint site code\n\nGenerated by the AI SharePoint extension from ${siteUrl}.\nFiles under \`lists/\`, \`pages/\`, and \`.aisharepoint/\` are managed by sync pulls — edit via\nSharePoint (then pull) rather than by hand until two-way push ships.\n`,
    ],
  ]);
}
